/control/verbose 2
/run/initialize

/vis/scene/create

/vis/open OGLIQt 800x800-0+0
#/vis/open OGLIX 800x800-0+0

#/vis/open OGL 800x800-0+0
#/vis/sceneHandler/create OGL
#/vis/sceneHandler/attach
#/vis/viewer/create ! ! 600
#/vis/viewer/refresh

#/vis/drawVolume
#/vis/viewer/set/viewpointThetaPhi 115 65 # angled view
#/vis/viewer/set/viewpointThetaPhi 0 0 # front view
/vis/viewer/set/viewpointThetaPhi -90 -89 # top view
#/vis/viewer/set/viewpointThetaPhi 90 0 # side view
#/vis/viewer/zoom 0.5
#/vis/viewer/set/style wireframe
#/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/trajectories rich smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
#/vis/scene/add/hits
#/vis/scene/endOfEventAction accumulate 2 
#/vis/ogl/set/displayListLimit 50000

/vis/scene/add/volume
/vis/sceneHandler/attach
#/vis/viewer/flush
/vis/scene/add/trajectories
/vis/scene/add/hits

